---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - shell: ENDPOINT={{endpoint_v3}} USERNAME={{admin_user}} PASSWORD={{admin_password}} TENANT=admin DOMAIN={{domain}} /opt/xos/openstack/get_token.sh
    register: token

  - shell: ID=$(/usr/bin/glance --os-image-url={{image_url}} --os-auth-token={{ '{{' }} token.stdout {{ '}}' }}  image-create --name="{{name}}" --disk-format=raw --is-public=True --file="{{filepath}}") && echo "{\"id\": \"$ID\" }" | python -m json.tool 
